### ISSUE TITLE
Proč jsi změnil repozitář?

### ISSUE THREAD

**Issue by fan1x** [Ji59/IMG_to_txt_form_app#1]

**Comment by Ji59** [comment]
Ctěl jsem začít od znova a také jsem měl špatně nastavený a synchronizovaný git. Řekl jsem si, že bude lepší založit nový, než řešit problémy se synchronizací nového projektu, apod.

**Comment by Ji59** [comment]
To je taky pravda, že jsem nevěděl u toho prvního, jak to udělat. Ale teď mám naimportovaný git do visual studio a všeje jednodušší.
