### ISSUE TITLE
Lépe pojmenovat třídy, proměnné

### ISSUE THREAD

**Issue by fan1x** [Ji59/IMG_to_txt_form_app#3]
Například: https://github.com/Ji59/IMG_to_txt_form_app/blob/b4c2747f19ba9b3b764ca70c14bd0adbfc1a0491/IMG_to_txt_firm_app/Form1.cs#L12

https://github.com/Ji59/IMG_to_txt_form_app/blob/b4c2747f19ba9b3b764ca70c14bd0adbfc1a0491/IMG_to_txt_firm_app/Form1.cs#L13

jméno `const1` je úplně k ničemu 😄 nahradit něčím výstižnějším... Kde je ta konstanta použita, co znamená?

**Comment by Ji59** [comment]
Refactoring proveden, přejmenovány konstanty, ale najít vhodné nové jméno bylo težké
