### ISSUE TITLE
Proč je šířka zrovna 8 násobek?

### ISSUE THREAD

**Issue by fan1x** [Ji59/IMG_to_txt_form_app#6]
Změnit, aby to šlo nastavit jako jeden z parametrů uživatele

**Comment by Ji59** [comment]
Já jsem na internetu našel bitmapy jednotlivých znaků, které mají rozměry 8x8. Uživatel zadá počet znaků na řádek a z toho důvodu je původní obrázek převeden na osminásobek zadané hodnoty. Poté lze přesně rozdělit obrázek na zadaný počet znaků a porovnávat pixel ku pixelu. Jinak nevidím žádnou výhodu toho, že by to mohl uživatel ovlivňovat.
